version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: php-todo-web
    working_dir: /var/www/html
    environment:
      MYSQL_IP: ${MYSQL_IP}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
    ports:
      - "8082:80"  # Change the port mapping here
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    command: >
      /bin/sh -c "
      apt-get update && apt-get install -y zip unzip git && 
      docker-php-ext-install mysqli && 
      a2enmod rewrite && 
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      composer install --ignore-platform-reqs &&
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan config:cache &&
      apache2-foreground
      "

  db:
    image: mysql:5.7
    container_name: php-todo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
