version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
    environment:
      MYSQL_IP: db
      MYSQL_USER: lourash
      MYSQL_PASS: Password@123
      MYSQL_DBNAME: toolingdb
      MYSQL_ROOT_PASSWORD: Password@123
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: lourash
      MYSQL_PASSWORD: Password@123
      MYSQL_ROOT_PASSWORD: Password@123
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db:
